### PR TITLE
refactor: update sass-rem

### PR DESCRIPTION
**Pull request by borisdamevin**
Update the missing code to new sass-rem.

### CODE REVIEW

**Comment by Romakita** [comment]
Hello @borisdamevin 
Thanks for your PR. But This change is required ? 
I don't see a difference between yesterday and I'm afraid to have the same result with the website :)

See you
Romain

**Comment by borisdamevin** [comment]
My first PR about that forgot many files to change old sass-rem mixin to new with dart sass, but I check in local serve and all is good for me now.

Of course is your final decision :).

**Comment by borisdamevin** [comment]
image

**Comment by Romakita** [comment]
ok, I think it's fine for merge it. This is small conflict on package.json and yarn.lock :)

**Comment by borisdamevin** [comment]
@Romakita Conflicts resolved!

Thank you!

**Pull request merged**
